In [2]:
#to swap LDA for NMF 

In [3]:
import pandas as pd
npr=pd.read_csv("npr.csv")

In [4]:
#we extract features and display the topics

In [5]:
#2 main topics
#1.Preprocessing feature extraction

#LDA is dependent  on per word count probabiblites, we can only use count vectoriser

#but since Non negative Matrix factorisation, works with coefficients of values
#we can preprocess the text with TFIDF vectorisation

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tfidf=TfidfVectorizer(max_df=0.95, min_df=2,stop_words='english')
#ask for words, with not more than 95 % #must show up atleast 10% or 2 as number of words
#tifid, will remove the stop words for us

In [9]:
npr['Article']
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [10]:
dtm= tfidf.fit_transform(npr['Article'])

In [21]:
dtm
#sparse matrix, 


  (0, 162)	0.024207779726177357
  (0, 436)	0.057426739142936806
  (0, 604)	0.02813089107375169
  (0, 650)	0.02653652777634086
  (0, 1288)	0.022444232597226593
  (0, 1434)	0.028763633914840988
  (0, 1489)	0.023797160985101373
  (0, 1608)	0.03226897967994957
  (0, 1610)	0.020693641331932494
  (0, 1613)	0.07253465437685631
  (0, 1632)	0.025308912294465642
  (0, 1674)	0.01910359684823228
  (0, 1762)	0.017698767416640195
  (0, 1884)	0.025404296400493534
  (0, 1932)	0.027002284256125594
  (0, 1993)	0.044568871723068636
  (0, 2045)	0.07533311505887272
  (0, 2060)	0.0383433531113439
  (0, 2084)	0.015039386128760875
  (0, 2093)	0.04883763812854993
  (0, 2347)	0.03491292226818417
  (0, 2437)	0.05672110592908613
  (0, 2491)	0.04202580292018094
  (0, 2525)	0.028380087248686597
  (0, 2689)	0.016700219215567812
  :	:
  (11991, 52783)	0.15232527696882306
  (11991, 52786)	0.032524386440987
  (11991, 52788)	0.03858014866091516
  (11991, 52977)	0.05145632144946742
  (11991, 53014)	0.009862718553798772
 

In [13]:
from sklearn.decomposition import NMF

In [22]:
nmf_model = NMF(n_components=7,random_state=42)
nmf_model

NMF(n_components=7, random_state=42)

In [23]:
nmf_model.fit(dtm)
nmf_model.components_

array([[0.00000000e+00, 2.49950821e-01, 0.00000000e+00, ...,
        1.70313822e-03, 2.37544362e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.22048918e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 3.12379960e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.89723338e-03, 0.00000000e+00, 1.50186440e-03, ...,
        7.06428924e-04, 5.85500542e-04, 6.89536542e-04],
       [4.01763234e-03, 5.31643833e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [16]:
#nmf performs faster than LDA , 
#because the way the numpy works

In [18]:
tfidf.get_feature_names()[2300]

'albala'

In [20]:
#we will get top 15 words per a topic
for index, topic in enumerate(nmf_model.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print("\n")

THE TOP 15 WORDS FOR TOPIC #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP 15 WORDS FOR TOPIC #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP 15 WORDS FOR TOPIC #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['love', 've', 'don', 'al

In [24]:
topic_results = nmf_model.transform(dtm)

In [27]:
topic_results.shape
#it is the coefficient value for the top topics
dtm.shape

(11992, 54777)

In [31]:
topic_results[0].argmax()
#index position for the most representative target or topic 

1

In [32]:
topic_results[0]

array([0.        , 0.12075603, 0.00140297, 0.05919954, 0.01518909,
       0.        , 0.        ])

In [29]:
#if we want to do this across the columns

In [34]:
topic_results.argmax(axis=1)
#along the columns

array([1, 1, 1, ..., 0, 4, 3], dtype=int64)

In [35]:
npr['Topic']=topic_results.argmax(axis=1)

In [36]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6

In [37]:
#the main thing, we need to do as, 
#we need to label the topics
#ex, topic 6 can be education

In [38]:
myTopicDictionary= {0:'health',1:'elec',2:'legis',3:'politic',4:'elec',5:'music',6:'edu'}
npr['Topic Label'] = npr['Topic'].map(myTopicDictionary)

In [39]:
npr.head()

Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      1        elec
1    Donald Trump has used Twitter  —   his prefe...      1        elec
2    Donald Trump is unabashedly praising Russian...      1        elec
3  Updated at 2:50 p. m. ET, Russian President Vl...      3     politic
4  From photography, illustration and video, to d...      6         edu