In [80]:
import pandas as pd

In [82]:
npr= pd.read_csv('npr.csv')

In [84]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [86]:
# here we only have information, on the article, text, 

In [88]:
#we dont have any labels

In [90]:
# npr['Article'][0]
len(npr)

11992

In [92]:
#we dont know is, what actual topics these articles belong to

In [94]:
#we need to run little bit of preprocessing before LDA

In [96]:
from sklearn.feature_extraction.text import CountVectorizer

In [97]:
cv=CountVectorizer(max_df=0.9,min_df=2,stop_words='english')
#we need to get rid of words, which have high document frequency
# in simple way, gets rid of words, which are common in documents
#so we pass max_df=0.9

#words that show, up minimum number of times = 2 ,
#this says that minimum number of frequency of words should be atleast 2 in doucments

#we can also remove stop words, by adding the stop_words argument

In [98]:
#now we need to apply this , and fit transform for this article

In [99]:
#now we cant do , train_test_split, because this is unsuoervised learning
#since we dont have any labels
# so we are going to do fit transform to the entire article

In [100]:
dtm=cv.fit_transform(npr['Article'])
#dtm (document term matrix)

In [101]:
dtm
#returns  a sparse matrix
print(dtm)

  (0, 53112)	2
  (0, 436)	3
  (0, 37382)	2
  (0, 5867)	1
  (0, 37411)	2
  (0, 43740)	1
  (0, 54403)	3
  (0, 44460)	2
  (0, 28875)	3
  (0, 44648)	1
  (0, 16578)	1
  (0, 12950)	1
  (0, 604)	1
  (0, 38079)	6
  (0, 34145)	15
  (0, 32459)	1
  (0, 42732)	1
  (0, 42390)	9
  (0, 2437)	2
  (0, 25508)	5
  (0, 16123)	4
  (0, 26752)	3
  (0, 10646)	1
  (0, 41011)	4
  (0, 29070)	1
  :	:
  (11991, 4315)	1
  (11991, 28887)	1
  (11991, 32585)	1
  (11991, 50599)	1
  (11991, 9067)	1
  (11991, 38652)	1
  (11991, 47768)	2
  (11991, 33536)	1
  (11991, 16527)	1
  (11991, 41081)	1
  (11991, 14611)	1
  (11991, 28356)	1
  (11991, 35785)	1
  (11991, 33620)	14
  (11991, 7316)	1
  (11991, 45088)	1
  (11991, 22720)	1
  (11991, 51838)	1
  (11991, 37235)	1
  (11991, 49654)	1
  (11991, 15275)	1
  (11991, 53567)	1
  (11991, 12752)	1
  (11991, 20202)	1
  (11991, 47633)	11


In [102]:
#now we need to do LDA

In [103]:
from sklearn.decomposition import LatentDirichletAllocation

In [104]:
LDA = LatentDirichletAllocation( n_components=7 , random_state=42)
# n_components=7 , 7 general topics
print(LDA)

LatentDirichletAllocation(n_components=7, random_state=42)


In [105]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [106]:
#LDA, is an iterative words
#it is going to keep updating the weights of the words , and topics, until they are 
#stabilized

In [107]:
#Grab the vocabulary of the words
len(cv.get_feature_names())

54777

In [108]:
type(cv.get_feature_names())

cv.get_feature_names()[5005]
#we could print random words from this list

import random

randomr_word_id= random.randint(0,54777)

cv.get_feature_names()[randomr_word_id]

'bathrooms'

In [109]:
#Grab the topics

len(LDA.components_)

type(LDA.components_)
#it is an array ,containing, the

LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [110]:
single_topic = LDA.components_[0]

single_topic.argsort()
#arg sort, returns the index positions that would sort this array

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [111]:
import numpy as np

arr = np.array([10,200,1])
arr

arr.argsort()
#it would return the index positions from the lowest value to the highest value

#argsort, is returning the locations, of the larger values, 
# we can use this index positions, and get correlated with the feature_names


array([2, 0, 1], dtype=int64)

In [112]:
# ARGSORT ----> INDEX POSITIONS FROM LEAST --> GREATES
#TOP 10 VALUES (10 GREATEST VALUES)
#LAST 10 VALUES OF ARGSORT()

single_topic.argsort()[-10:] #grab the last 10 values of the .argsort()
#top 10 words

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [113]:
top_ten_words = single_topic.argsort()[-10:]

for index in top_ten_words:
    print(cv.get_feature_names()[index])
    

    #LDA is showing us some underlined labelled topics
    #these words have high probability, in particular, single_topic

new
percent
government
company
million
care
people
health
said
says


In [114]:
#Grab the highest probability words per topic

for i,topic in enumerate(LDA.components_):
    print(f"The Top 15 words for topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The Top 15 words for topic #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The Top 15 words for topic #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The Top 15 words for topic #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The Top 15 words for topic #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The Top 15 words for topic #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The Top 15 words for topic #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know'

In [122]:
dtm.shape

(11992, 54777)

In [120]:
#now we need to attatch the topic number as a  new column to the original article

topic_results =LDA.transform(dtm)
print(topic_results)
topic_results.shape

[[1.61040465e-02 6.83341493e-01 2.25376318e-04 ... 2.99652737e-01
  2.25479379e-04 2.25497980e-04]
 [3.63424997e-02 8.86130697e-01 4.40751747e-04 ... 7.57636804e-02
  4.40866779e-04 4.40835574e-04]
 [3.28569485e-04 6.96344889e-01 3.28302105e-04 ... 3.02012902e-01
  3.28724083e-04 3.28352652e-04]
 ...
 [1.44467964e-02 1.60696622e-01 1.73678310e-01 ... 2.24636569e-02
  3.98728349e-04 3.98359730e-04]
 [4.33560738e-04 3.53196803e-02 4.33022554e-04 ... 9.62512640e-01
  4.33971991e-04 4.33490254e-04]
 [3.98777533e-01 2.54376049e-04 3.59290659e-01 ... 2.40914375e-01
  2.54445555e-04 2.54253739e-04]]


(11992, 7)

In [117]:
topic_results.shape

topic_results[0]
#these are probabilites, of a documents, belonging to a topic
#probabilities 

topic_results[0].round(2)
#we can also round off

#here we are interested only in the index positions of the highest probabilites
topic_results[0].argmax()

1

In [118]:
npr['Topic']=topic_results.argmax(axis=1)

In [119]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]