In [2]:
import pickle
import numpy as np

In [3]:
with open("test_qa.txt",'rb') as f:
    test_data = pickle.load(f)
    #we need to read it as binary, so we needed pickle

In [4]:
with open("train_qa.txt",'rb') as f:
    train_data = pickle.load(f)

In [5]:
type(test_data)

list

In [6]:
type(train_data)

list

In [7]:
len(train_data)

10000

In [8]:
len(test_data)

1000

In [9]:
train_data
#they are list of tuples  
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [10]:
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [11]:
' '.join(train_data[0][1])

'Is Sandra in the hallway ?'

In [12]:
(train_data[0][2])

'no'

In [13]:
test_data

[(['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.',
   'Daniel',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'garden', '?'],
  'yes'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',


In [14]:
#we need to setup a vocubalry of all the words in the dataset
# we should also take train and test data

In [15]:
#lets create a vocabulary
all_data = test_data + train_data

In [16]:
len(all_data)

11000

In [17]:
#we need to set in python , to add wordds in set , so that we get all unique words

In [18]:
set(train_data[0][0])

{'.',
 'Mary',
 'Sandra',
 'bathroom',
 'bedroom',
 'journeyed',
 'moved',
 'the',
 'to'}

In [19]:
vocab=set()#creating an empty set

for story,question,answer in all_data:
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

In [20]:
vocab.add('no')
vocab.add('yes')

In [21]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [22]:
vocab_len = len(vocab)+1 #since we have a placeholder, when we are working with keras

In [23]:
vocab_len

38

In [24]:
all_data
# tuple_1= (1,2,3)
# len(tuple_1)

[(['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.',
   'Daniel',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'garden', '?'],
  'yes'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',


In [25]:
#Longest story
all_story_lens = [ len(data[0]) for data in all_data ] 

In [26]:
max_story_len = max(all_story_lens)

In [27]:
max_question_len =  max([len(data[1]) for data in all_data ])

In [28]:
#we explored data, opened it up, saw that it is a list, where list item is a tuple
#with story, quesiton, answer .
#we built out a vocabular ywith set , and union
#we added no and yes
#we built a vocaulary with set
#we added the union of question and story
# unitl we had all unqieu words present in our connections in our story
#and we also added no and yes as possible answwer
#and we calculated longest story and lingest quesiton
#we use this, for keras pad sequences, once we vectorise the data

#so we explore keras preprocessing for padding sequences and tokenizer

In [29]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [30]:
#create an integer, encoding with sequence of words

In [31]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [32]:
tokenizer.word_index
#a dictionary that maps every word in our vaovulary set to a unique number

{'mary': 1,
 'no': 2,
 'down': 3,
 'is': 4,
 'moved': 5,
 'john': 6,
 'journeyed': 7,
 'bedroom': 8,
 'football': 9,
 'apple': 10,
 'there': 11,
 'got': 12,
 'took': 13,
 'discarded': 14,
 'bathroom': 15,
 'back': 16,
 'sandra': 17,
 '.': 18,
 'put': 19,
 'hallway': 20,
 'kitchen': 21,
 'up': 22,
 'grabbed': 23,
 'the': 24,
 '?': 25,
 'garden': 26,
 'in': 27,
 'to': 28,
 'left': 29,
 'dropped': 30,
 'daniel': 31,
 'went': 32,
 'yes': 33,
 'milk': 34,
 'office': 35,
 'travelled': 36,
 'picked': 37}

In [33]:
#we will create  a function that vectrises the storeis for us automatically

In [34]:
train_story_text = []
train_question_text = []
train_answers = []

In [35]:
for story,question,answer in train_data:
    train_story_text.append(story)
    train_question_text.append(question)
    train_answers.append(answer)

In [36]:
train_story_text
#we have seperated, the stores, questions and answers from the train_data

[['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.',
  'Sandra',
  'went',
  'to',
  'the',
  'kitchen',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'bathroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to

In [37]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [38]:
len(train_story_seq)

10000

In [39]:
train_story_seq
#we have converted into index calls

[[1, 5, 28, 24, 15, 18, 17, 7, 28, 24, 8, 18],
 [1,
  5,
  28,
  24,
  15,
  18,
  17,
  7,
  28,
  24,
  8,
  18,
  1,
  32,
  16,
  28,
  24,
  8,
  18,
  31,
  32,
  16,
  28,
  24,
  20,
  18],
 [1,
  5,
  28,
  24,
  15,
  18,
  17,
  7,
  28,
  24,
  8,
  18,
  1,
  32,
  16,
  28,
  24,
  8,
  18,
  31,
  32,
  16,
  28,
  24,
  20,
  18,
  17,
  32,
  28,
  24,
  21,
  18,
  31,
  32,
  16,
  28,
  24,
  15,
  18],
 [1,
  5,
  28,
  24,
  15,
  18,
  17,
  7,
  28,
  24,
  8,
  18,
  1,
  32,
  16,
  28,
  24,
  8,
  18,
  31,
  32,
  16,
  28,
  24,
  20,
  18,
  17,
  32,
  28,
  24,
  21,
  18,
  31,
  32,
  16,
  28,
  24,
  15,
  18,
  31,
  37,
  22,
  24,
  9,
  11,
  18,
  31,
  32,
  28,
  24,
  8,
  18],
 [1,
  5,
  28,
  24,
  15,
  18,
  17,
  7,
  28,
  24,
  8,
  18,
  1,
  32,
  16,
  28,
  24,
  8,
  18,
  31,
  32,
  16,
  28,
  24,
  20,
  18,
  17,
  32,
  28,
  24,
  21,
  18,
  31,
  32,
  16,
  28,
  24,
  15,
  18,
  31,
  37,
  22,
  24,
  9,
  11,
  18,

In [40]:
#create a function that helps in vectorising the stories

In [41]:
#we need max story len and max question len
#since we need to adjust the data by adding 0s or cutting it down for the padding sequences
def vectorize_stories(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_question_len=max_question_len):
    #stories = X
    X =[]
    # questions = Xq
    Xq = []
    #target(correct answer) (yes/no)
    Y=[]
    
    for story,query,answer in data:
        #for each story 
        # [23,14,....]
        x=[word_index[word.lower()] for word in story]
        xq=[word_index[word.lower()] for word in query]
        
        y = np.zeros(len(word_index) + 1)
        #index 0 is reserved for pad sequences 
        
        y[word_index[answer]]=1
        
        X.append(x)
        Xq.append(xq)
        Y.append(y)
        
    return (pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq,maxlen=max_question_len),np.array(Y))

In [42]:
#we are vectorisign the stories

In [43]:
inputs_train,queries_train,answers_train = vectorize_stories(train_data)

In [44]:
inputs_test,queries_test,answers_test = vectorize_stories(test_data)

In [45]:
inputs_test

array([[ 0,  0,  0, ..., 24,  8, 18],
       [ 0,  0,  0, ..., 24, 26, 18],
       [ 0,  0,  0, ..., 24, 26, 18],
       ...,
       [ 0,  0,  0, ..., 24, 10, 18],
       [ 0,  0,  0, ..., 24, 26, 18],
       [ 0,  0,  0, ..., 10, 11, 18]])

In [46]:
answers_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
sum(answers_test)

array([  0.,   0., 503.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
       497.,   0.,   0.,   0.,   0.])

In [48]:
#we have successfully vectorised our stories,qeustions, ans anwers
#we have data in correct format for creating model

In [49]:
#next we will create the model with keras layers
from keras.models import Sequential,Model

In [50]:
from keras.layers.embeddings import Embedding

In [51]:
from keras.layers import Input,Activation,Dense,Permute,Dropout,add,dot,concatenate,LSTM

In [52]:
#we need to hold up in placeholder
#we also have stores and quesitons
#we have stories , which encoder needs to understaand 
#then a seperate queston, and we need to link them together to provide a label, 'yes' or 'no'

In [63]:
#we are going to create placeholders using  input
#the input funciton of keras, is going to instantiate a tensor
input_sequence = Input((max_story_len,))
#and we have to add the shape , so we add max_story_len and we are saying ,
#we added ","  since PLACEHOLDER shape = (max_story_len,batch_size)
#since we dont know the size of the batch_Size, we have left it (or we didnt define it)
question = Input((max_question_len,))
#these are placeholdrers ready to recive input of  stories and questions

In [64]:
#now we need to create input encoders
#we need to define vocabulary size
vocab_size = len(vocab) + 1
#vocab_len

In [65]:
#we  need to continue for  INOUT ENCODER M
input_encoder_m = Sequential()
#this input gets embedded into sequence of vectors
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
#we are adding embedding layer, we are giving vocab size, and output_dim
input_encoder_m.add(Dropout(0.3))
#add a dropout layer,percentage of nuerons are dropped of

#OUTPUT
#{sample,story_maxlen,embedding_dim}

In [66]:
#we need to copy and paste for input encoder C 

input_encoder_c = Sequential()
#this input gets embedded into sequence of vectors
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
#we are adding embedding layer, we are giving vocab size, and output_dim
input_encoder_c.add(Dropout(0.3))
#add a dropout layer,percentage of nuerons are dropped of

#OUTPUT
#{sample,story_maxlen,embedding_dim}

In [67]:
#question encoder

question_encoder = Sequential()
#this input gets embedded into sequence of vectors
question_encoder.add(Embedding(input_dim=vocab_size,output_dim=64,input_length=max_question_len))
#we are adding embedding layer, we are giving vocab size, and output_dim
question_encoder.add(Dropout(0.3))
#add a dropout layer,percentage of nuerons are dropped of

#OUTPUT
#{samples,query_maxlen,embedding_dim}

In [68]:
#now that we have the input encoder m, and inputencoder c and quesiton encoder

In [69]:
#we need to encode the sequences 

In [70]:
#we alreadyhave placeholders (input_sequence, question)
#we need to pass the placeholders into the input encoders m, c and question encoder

In [76]:

#result after passing through the encoder

#encoded <---- encoder(input)
input_encoded_m = input_encoder_m(input_sequence)
input_encoded_c=input_encoder_c(input_sequence)
question_encoded=question_encoder(question)


In [78]:
#we just need to use the dot product to compute the match b/w the first input sequence vector 
#and the query
match = dot([input_encoded_m,question_encoded],axes=(2,2))
#as a list, we pass the two eleemnts which we want to compare
match=Activation('softmax')(match)

In [79]:
response = add([match,input_encoded_c])
response=Permute((2,1))(response)

In [80]:
#once we have a response, we can concatenate the match matrix with question matrix sequence

In [81]:
answer = concatenate([response,question_encoded])

In [82]:
answer

<tf.Tensor 'concatenate/concat:0' shape=(None, 6, 220) dtype=float32>

In [83]:
#we want to reduce it with a recurrent layer, we  are using LSTM layer specifically for it

In [85]:
from keras.layers.recurrent import LSTM
answer = LSTM(32)(answer)

NotImplementedError: Cannot convert a symbolic Tensor (lstm_1/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

In [87]:
#we are performing one more series of regulrisation with dropout
answer = Dropout(0.5)(answer)
answer = Dense(vocab_size)(answer)
#(sample,vocab_size) #YES/NO 0000

ValueError: Attempt to convert a value (<tensorflow.python.keras.layers.core.Dropout object at 0x000002566A1E7190>) with an unsupported type (<class 'tensorflow.python.keras.layers.core.Dropout'>) to a Tensor.

In [88]:
answer = Activation('softmax')(answer)

AttributeError: 'Dropout' object has no attribute 'shape'

In [89]:
# we will need to output a proability distribution over the vocabulary, because we see , a bunch of 0 , except some probabilites on yes /no
#so we will pass them into softmax,to turn them into 0 or 1
answer = Activation('softmax')(answer)

AttributeError: 'Dropout' object has no attribute 'shape'

In [90]:
model = Model([input_sequence,question],answer)

AttributeError: 'Dropout' object has no attribute 'op'

In [91]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy')

NameError: name 'model' is not defined

In [92]:
#we are doing this compilation accros entire voacbulary,
#we should expect only yes/no

In [94]:
#now we need to fit the model
history = model.fit([inputs_train,queries_train],answers_train,batch_size=32,epochs=3,validation_data=([inputs_test,queries_test],answers_test))
#we are training on input stories and input questions
#100 epochs ~ 6000 seconds

NameError: name 'model' is not defined

In [96]:
import matplotlib.pyplot as plt
%matplotlib inline
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

NameError: name 'history' is not defined

In [97]:
#load model
model.load_weights('chatbot_10.h5')

NameError: name 'model' is not defined

In [98]:
pred_results = model.predict(([inputs_test,queries_test]))

NameError: name 'model' is not defined

In [101]:
test_data
#its tuples, story , question and answer
test_data[0][0]

['Mary',
 'got',
 'the',
 'milk',
 'there',
 '.',
 'John',
 'moved',
 'to',
 'the',
 'bedroom',
 '.']

In [103]:
pred_results
#it has probability for every single word

NameError: name 'pred_results' is not defined

In [104]:
val_max = np.argmax(pred_results[0])

NameError: name 'pred_results' is not defined

In [106]:
for key,val in tokenizer.word_index.items():
    if val == val_max:
        k=key

NameError: name 'val_max' is not defined

In [107]:
k

NameError: name 'k' is not defined

In [108]:
pred_results[0][val_max]

NameError: name 'pred_results' is not defined

In [109]:
my_story = "John left the kitchen . Sandra dropped the football in the garden ."

In [113]:
my_story.split()

['John',
 'left',
 'the',
 'kitchen',
 '.',
 'Sandra',
 'dropped',
 'the',
 'football',
 'in',
 'the',
 'garden',
 '.']

In [114]:
my_question="Is the football in the garden ?"

In [115]:
my_question.split()

['Is', 'the', 'football', 'in', 'the', 'garden', '?']

In [116]:
#new data set of onequesiton, story and answer and pass to vectorised data funciton
my_data = [(my_story.split() , my_question.split(), 'yes')]

In [117]:
my_data

[(['John',
   'left',
   'the',
   'kitchen',
   '.',
   'Sandra',
   'dropped',
   'the',
   'football',
   'in',
   'the',
   'garden',
   '.'],
  ['Is', 'the', 'football', 'in', 'the', 'garden', '?'],
  'yes')]

In [118]:
my_story,my_ques,my_ans = vectorize_stories(my_data)

In [119]:
my_story
#same for my_quesiton, my_ans

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,
        29, 24, 21, 18, 17, 30, 24,  9, 27, 24, 26, 18]])

In [120]:
#call the model and predict on new set of data
pred_results = model.predict(([my_story,my_ques]  ))

NameError: name 'model' is not defined

In [121]:
val_max = np.argmax(pred_results)[0]

NameError: name 'pred_results' is not defined

In [122]:
for key,val in tokenizer.word_index.items():
    if val == val_max:
        k=key

NameError: name 'val_max' is not defined

In [123]:
k

NameError: name 'k' is not defined

In [124]:
pred_results[0][val_max]

NameError: name 'pred_results' is not defined