In [3]:
import numpy as np

In [4]:
#read the dataset, it is built in the scikit learn
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
type(iris)
#it is a special bunch object returned by the scikit learn

sklearn.utils.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data

In [9]:
X
#- sepal length in cm
        #- sepal width in cm
        # petal length in cm
        #- petal width in cm

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y=iris.target

In [11]:
y
#class 0 , class 1, class 2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
# because  of the way keras and neural networks , we want the data to convert into
#categorical data

In [13]:
# class 0 ---> [1,0,0]  
# class 1 ---> [0,1,0]  
# class 2 ---> [0,0,1]

# this is 1 hardcoding, and we will be able to do this easily, with built in functions in keras

In [14]:
from keras.utils import to_categorical

In [15]:
y = to_categorical(y)

In [16]:
y.shape

(150, 3)

In [17]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [18]:
#we can continue on to split the data intro training and testing data for keras

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
X_train
X_test
y_train
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [22]:
#to scale or standardize the data
from sklearn.preprocessing import MinMaxScaler

In [23]:
# it makes all the values fit between a range like 0 to 1, or -1 to 1, 
#it essentially divides all the values with the max value

In [24]:
np.array([510,15,20])/20

array([25.5 ,  0.75,  1.  ])

In [25]:
scalar_object = MinMaxScaler()

In [26]:
#fit the scalar object to training data, because we dont want to cheat, or asusme the prior knowledge test data
scalar_object.fit(X_train)

MinMaxScaler()

In [27]:
#then we are going to create sclaed versions of our training data
scalar_X_train = scalar_object.transform(X_train)

In [28]:
scaled_X_test = scalar_object.transform(X_test)

In [29]:
# scaled_X_test
#now we have the sclaed versions of the data

In [30]:
#now we will build the network with keras

In [31]:
from keras.models import Sequential
from keras.layers import Dense

In [32]:
model= Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))#input layer
#units=8 (8 neurons) ( we chose a multiple of number of features), we are expecting 4 features, activation function is reactified linear unit
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))#output layer#[0.2,0.3,0.5]

# at the end, the neuron will return 30% chances for the first index value, 30% for second and 40% for the remaining
#we compile our model at the end
# we choose sort of loss, it depends on what you choose,
#we are doing categorical process, so we will say, categorical_crossentropy

In [33]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(scalar_X_train,y_train,epochs=150,verbose=2)
#epoch is trunning through an entire dataset
#verbose, is how much output u want information
#0 it is not gonna work for anhting
#1 for progress bar
#2 for loss, and accuray on epochs

Epoch 1/150
4/4 - 0s - loss: 1.2632 - accuracy: 0.3100
Epoch 2/150
4/4 - 0s - loss: 1.2246 - accuracy: 0.3100
Epoch 3/150
4/4 - 0s - loss: 1.1943 - accuracy: 0.3000
Epoch 4/150
4/4 - 0s - loss: 1.1660 - accuracy: 0.2900
Epoch 5/150
4/4 - 0s - loss: 1.1408 - accuracy: 0.2700
Epoch 6/150
4/4 - 0s - loss: 1.1182 - accuracy: 0.2500
Epoch 7/150
4/4 - 0s - loss: 1.0965 - accuracy: 0.3200
Epoch 8/150
4/4 - 0s - loss: 1.0781 - accuracy: 0.4400
Epoch 9/150
4/4 - 0s - loss: 1.0595 - accuracy: 0.5300
Epoch 10/150
4/4 - 0s - loss: 1.0441 - accuracy: 0.5300
Epoch 11/150
4/4 - 0s - loss: 1.0283 - accuracy: 0.5200
Epoch 12/150
4/4 - 0s - loss: 1.0145 - accuracy: 0.5400
Epoch 13/150
4/4 - 0s - loss: 1.0024 - accuracy: 0.5500
Epoch 14/150
4/4 - 0s - loss: 0.9905 - accuracy: 0.5700
Epoch 15/150
4/4 - 0s - loss: 0.9791 - accuracy: 0.6100
Epoch 16/150
4/4 - 0s - loss: 0.9685 - accuracy: 0.6200
Epoch 17/150
4/4 - 0s - loss: 0.9581 - accuracy: 0.6200
Epoch 18/150
4/4 - 0s - loss: 0.9485 - accuracy: 0.6200
E

Epoch 147/150
4/4 - 0s - loss: 0.4157 - accuracy: 0.8400
Epoch 148/150
4/4 - 0s - loss: 0.4141 - accuracy: 0.8600
Epoch 149/150
4/4 - 0s - loss: 0.4135 - accuracy: 0.8800
Epoch 150/150
4/4 - 0s - loss: 0.4115 - accuracy: 0.8900


In [36]:
#how do we predict on new unseen data, and how to evaluate the model performance

In [37]:
#we first need to scale our test data, for new incoming data
#we already done that, 
#but if we have fresh data, we have to scale the data firs,because our model 
#is trained on the scaled data

In [38]:
model.predict(scaled_X_test)

array([[1.20029887e-02, 5.15042782e-01, 4.72954214e-01],
       [9.69126284e-01, 1.70237776e-02, 1.38499327e-02],
       [3.04159679e-04, 2.31192693e-01, 7.68503189e-01],
       [1.10599399e-02, 4.84448493e-01, 5.04491508e-01],
       [5.71940420e-03, 4.38603044e-01, 5.55677533e-01],
       [9.44424510e-01, 3.15948054e-02, 2.39806976e-02],
       [4.27761897e-02, 5.20690680e-01, 4.36533123e-01],
       [1.89828547e-03, 3.14816892e-01, 6.83284760e-01],
       [7.26801297e-03, 4.16304380e-01, 5.76427579e-01],
       [2.21258737e-02, 5.32952547e-01, 4.44921553e-01],
       [3.69819649e-03, 3.90530825e-01, 6.05770946e-01],
       [9.39577937e-01, 3.51316482e-02, 2.52904948e-02],
       [9.65281844e-01, 1.93998180e-02, 1.53183425e-02],
       [9.43926871e-01, 3.25262882e-02, 2.35468876e-02],
       [9.78956759e-01, 1.11114290e-02, 9.93179344e-03],
       [8.59405845e-03, 4.79255438e-01, 5.12150466e-01],
       [1.81112159e-03, 3.35509926e-01, 6.62678897e-01],
       [2.58250684e-02, 5.43473

In [48]:
#if we want the raw classes itself, 
predictions=model.predict_classes(scaled_X_test)

In [49]:
# y_test

In [50]:
#transform y_test data 

In [51]:
y_test.argmax(axis=1)
#it returns actual classes

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [52]:
#becuaese
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [53]:
#max value will be in the index posiiton of the corresponding class

In [54]:
#now we have preuctions, and original y values

In [55]:
#now we need to compare the predictions to the true values
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [56]:
# confusion
predictions

array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [57]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  6,  9],
       [ 0,  0, 16]], dtype=int64)

In [58]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.40      0.57        15
           2       0.64      1.00      0.78        16

    accuracy                           0.82        50
   macro avg       0.88      0.80      0.78        50
weighted avg       0.88      0.82      0.80        50



In [59]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.82


In [60]:
#here we have evaluated on unseen data
#now the last thing we want to do is

In [61]:
#if we are running a super large mode, like text generation
#we want to save and laod our model
model.save('myfirstmodel.h5')

In [62]:
#it saves all the weights, in that model

In [63]:
from keras.models import load_model

In [64]:
new_model=load_model('myfirstmodel.h5')

In [65]:
#we need to be careful with the saving , it can override

In [66]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [69]:
scaled_X_test


array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.